import React, { useState } from 'react';
import { Copy, Check, Download, FileText } from 'lucide-react';
import { downloadText } from '../utils/audioUtils';

interface TranscriptDisplayProps {
  text: string;
}

const TranscriptDisplay: React.FC<TranscriptDisplayProps> = ({ text }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    downloadText(text, `transcription-${new Date().toISOString().slice(0, 10)}.txt`);
  };

  // Advanced formatter to handle paragraphs and custom timestamp headers
  const renderFormattedText = () => {
    return text.split('\n').map((line, i) => {
      const trimmedLine = line.trim();
      if (!trimmedLine) return null;

      // Check for timestamp header pattern "## [MM:SS]"
      const timestampMatch = trimmedLine.match(/^##\s*\[(\d{2}:\d{2})\]/);
      
      if (timestampMatch) {
        return (
          <h2 key={i} className="text-2xl font-bold text-indigo-600 dark:text-indigo-400 mt-8 mb-4 border-b border-indigo-100 dark:border-indigo-500/20 pb-2 flex items-center">
            <span className="bg-indigo-50 dark:bg-indigo-500/10 px-2 py-1 rounded-md">{timestampMatch[1]}</span>
          </h2>
        );
      }
      
      // Standard paragraph
      return (
        <p key={i} className="mb-4 leading-relaxed text-slate-700 dark:text-slate-300">
          {trimmedLine}
        </p>
      );
    });
  };

  return (
    <div className="w-full bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 shadow-xl overflow-hidden flex flex-col h-[600px] transition-colors duration-300">
      <div className="p-4 border-b border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-900/50 flex items-center justify-between">
        <div className="flex items-center space-x-2 text-indigo-600 dark:text-indigo-400">
          <FileText size={18} />
          <h3 className="font-semibold text-slate-900 dark:text-slate-200">Transcription Result</h3>
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-white dark:bg-slate-800 hover:bg-gray-100 dark:hover:bg-slate-700 border border-gray-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 text-xs font-medium transition-colors"
          >
            {copied ? <Check size={14} className="text-green-500 dark:text-green-400" /> : <Copy size={14} />}
            <span>{copied ? 'Copied' : 'Copy'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium transition-colors shadow-lg shadow-indigo-500/20"
          >
            <Download size={14} />
            <span>Download</span>
          </button>
        </div>
      </div>
      
      <div className="flex-1 p-6 overflow-y-auto scrollbar-thin">
        <div className="prose prose-slate dark:prose-invert max-w-none">
          {renderFormattedText()}
        </div>
      </div>
      
      <div className="p-3 bg-gray-50 dark:bg-slate-900/30 border-t border-gray-200 dark:border-slate-700 text-center">
         <p className="text-xs text-slate-500">Generated by Gemini 2.5 Flash</p>
      </div>
    </div>
  );
};

export default TranscriptDisplay;